[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "pip install -r requirements.txt && gunicorn app:app"
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[volumes]
  directories = ["/images", "/content", "/news.db", "/gaming_news.json", "/app.log"]

[nixpacks]
  start-phase = "false"
  install-cmd = "pip install -r requirements.txt"

[http_service]
  internal_port = 8000
  force_https = true
  auto_start = true
  processes = ["app"]
